---
### IMPORTANT ###
#
#  Please note that you do not use Minecraft skins from 
#  https://de.namemc.com, they will be displayed incorrectly in the game.
#
#  Use skins from https://minecraftskins.com instead.
#
### IMPORTANT ###

# Please list all skins here. Pay attention to your spelling.
skins:
- GommeHD
- AbgegrieftHD

# Edit the news here.
messages:
    skin-success: "You just took the skin {name}."
    skin-reset: "You just reset your skin."
    skin-not-exist: "This skin doesn't exist."
    forms:
        main-form:
            title: "SlashSkin"
            description: "Choose what you want."
            button-1: "Skin List"
            button-2: "Reset your Skin"
        skin-list-form:
            title: "SlashSkin"
            description: "Choose your skin."
...
